require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module Phcpress
  RSpec.describe Modules::ConnectionsController, type: :controller do

    # This should return the minimal set of attributes required to create a valid
    # Modules::Connection. As you add validations to Modules::Connection, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {
      skip("Add a hash of attributes invalid for your model")
    }

    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # Modules::ConnectionsController. Be sure to keep this updated too.
    let(:valid_session) { {} }

    describe "GET #index" do
      it "assigns all modules_connections as @modules_connections" do
        connection = Modules::Connection.create! valid_attributes
        get :index, params: {}, session: valid_session
        expect(assigns(:modules_connections)).to eq([connection])
      end
    end

    describe "GET #show" do
      it "assigns the requested modules_connection as @modules_connection" do
        connection = Modules::Connection.create! valid_attributes
        get :show, params: {id: connection.to_param}, session: valid_session
        expect(assigns(:modules_connection)).to eq(connection)
      end
    end

    describe "GET #new" do
      it "assigns a new modules_connection as @modules_connection" do
        get :new, params: {}, session: valid_session
        expect(assigns(:modules_connection)).to be_a_new(Modules::Connection)
      end
    end

    describe "GET #edit" do
      it "assigns the requested modules_connection as @modules_connection" do
        connection = Modules::Connection.create! valid_attributes
        get :edit, params: {id: connection.to_param}, session: valid_session
        expect(assigns(:modules_connection)).to eq(connection)
      end
    end

    describe "POST #create" do
      context "with valid params" do
        it "creates a new Modules::Connection" do
          expect {
            post :create, params: {modules_connection: valid_attributes}, session: valid_session
          }.to change(Modules::Connection, :count).by(1)
        end

        it "assigns a newly created modules_connection as @modules_connection" do
          post :create, params: {modules_connection: valid_attributes}, session: valid_session
          expect(assigns(:modules_connection)).to be_a(Modules::Connection)
          expect(assigns(:modules_connection)).to be_persisted
        end

        it "redirects to the created modules_connection" do
          post :create, params: {modules_connection: valid_attributes}, session: valid_session
          expect(response).to redirect_to(Modules::Connection.last)
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved modules_connection as @modules_connection" do
          post :create, params: {modules_connection: invalid_attributes}, session: valid_session
          expect(assigns(:modules_connection)).to be_a_new(Modules::Connection)
        end

        it "re-renders the 'new' template" do
          post :create, params: {modules_connection: invalid_attributes}, session: valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested modules_connection" do
          connection = Modules::Connection.create! valid_attributes
          put :update, params: {id: connection.to_param, modules_connection: new_attributes}, session: valid_session
          connection.reload
          skip("Add assertions for updated state")
        end

        it "assigns the requested modules_connection as @modules_connection" do
          connection = Modules::Connection.create! valid_attributes
          put :update, params: {id: connection.to_param, modules_connection: valid_attributes}, session: valid_session
          expect(assigns(:modules_connection)).to eq(connection)
        end

        it "redirects to the modules_connection" do
          connection = Modules::Connection.create! valid_attributes
          put :update, params: {id: connection.to_param, modules_connection: valid_attributes}, session: valid_session
          expect(response).to redirect_to(connection)
        end
      end

      context "with invalid params" do
        it "assigns the modules_connection as @modules_connection" do
          connection = Modules::Connection.create! valid_attributes
          put :update, params: {id: connection.to_param, modules_connection: invalid_attributes}, session: valid_session
          expect(assigns(:modules_connection)).to eq(connection)
        end

        it "re-renders the 'edit' template" do
          connection = Modules::Connection.create! valid_attributes
          put :update, params: {id: connection.to_param, modules_connection: invalid_attributes}, session: valid_session
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE #destroy" do
      it "destroys the requested modules_connection" do
        connection = Modules::Connection.create! valid_attributes
        expect {
          delete :destroy, params: {id: connection.to_param}, session: valid_session
        }.to change(Modules::Connection, :count).by(-1)
      end

      it "redirects to the modules_connections list" do
        connection = Modules::Connection.create! valid_attributes
        delete :destroy, params: {id: connection.to_param}, session: valid_session
        expect(response).to redirect_to(modules_connections_url)
      end
    end

  end
end
